---
port: "8080"
owner: "www-data"
group: "www-data"
domain: "35.187.87.165"
mysql_root_password: "mysqlroot@123456"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "wordpress@123"
wp_url: "https://wordpress.org/wordpress-6.1.1.tar.gz"