---
- name: "wordpress installation"
  become: yes
  hosts: wordpress
  
  vars:
    php_version: '7.2'
  tasks:
    # Install php
    - name: Install php
      include_role:
        name: geerlingguy.php-versions
        name: geerlingguy.php

    # Install Apache
    - name: Install Apache
      include_role:
        name: geerlingguy.apache

    # Download & configure WordPress
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        remote_src: yes

    # Permission install wordpress
    - name: Set permissions on WordPress installation
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes