---
- name: "wordpress installation"
  become: yes
  hosts: wordpress

  tasks:
    # Install Apache
    - name: Install Apache
      include_role:
        name: geerlingguy.apache

    # Install php
    - name: Install php
      include_role:
        name: geerlingguy.php

    # Download & configure WordPress
    - name: Copy WordPress Files
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /var/www/html/wordpress.tar.gz
        owner: root
        group: root
        mode: '0644'
      notify:
        - Extract WordPress Files
    - name: remove default index.html
      file:
        path: /var/www/html/index.html
        state: absent
        
    - name: Désactiver le site par défaut
      command: a2dissite 000-default.conf
      notify:
        - Redémarrer Apache

  handlers:
    - name: Extract WordPress Files
      unarchive:
        src: /var/www/html/wordpress.tar.gz
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes
    - name: Enable WordPress Site
      command: a2ensite wordpress
    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted