---
- name: "wordpress installation"
  become: yes
  hosts: wordpress
  
  tasks:

    # Install Apache
    - name: Install Apache
      include_role:
        name: geerlingguy.apache
        name: geerlingguy.php

    # Download & configure WordPress
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        remote_src: yes

    # Permission install wordpress
    - name: Set permissions on WordPress installation
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes