---
- name: "wordpress installation"
  become: yes
  hosts: wordpress

  tasks:
    # Install Apache
    - name: Install Apache
      include_role:
        name: geerlingguy.apache

    # Install php
    - name: Install php
      include_role:
        name: geerlingguy.php

    # Download & configure WordPress
    - name: Copy WordPress Files
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /var/www/html/wordpress.tar.gz
        owner: root
        group: root
        mode: '0644'
      notify:
        - Extract WordPress Files

    # Permission install wordpress
    - name: Set permissions on WordPress installation
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes