- hosts: wordpress
  become: true

  roles:
    - role: geerlingguy.php
      become: true

    - role: geerlingguy.apache
      become: true

    - role: code_egg.openlitespeed_wordpress
      become: true
      
      vars:
        wordpress_version: latest
        wordpress_create_database: true
        wordpress_database_name: wp_db
        wordpress_database_user: wp_user
        wordpress_database_password: secretpassword